# Generated by Django 3.1.6 on 2021-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.TextField(default=''),
        ),
    ]
