# Generated by Django 3.2 on 2021-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceQuestion', '0002_auto_20210416_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='lecturer',
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
