# Generated by Django 3.2 on 2021-04-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceQuestion', '0004_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
