# Generated by Django 3.2 on 2021-04-21 22:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_related', '0003_auto_20210410_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practiceQuestion', '0006_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='UserAnswers',
        ),
    ]
