# Generated by Django 3.2 on 2021-04-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceQuestion', '0007_rename_answers_useranswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='score',
            field=models.CharField(max_length=50),
        ),
    ]
