# Generated by Django 3.2 on 2021-11-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_related', '0003_auto_20210410_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestionAnswerConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestionsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g Waec, Neco, GCE', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answers', models.ManyToManyField(through='past_question.PastQuestionAnswerConnector', to='past_question.PastQuestionsAnswer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past_question.questioncategory')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_related.subject')),
            ],
        ),
        migrations.AddField(
            model_name='pastquestionanswerconnector',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past_question.pastquestionsanswer'),
        ),
        migrations.AddField(
            model_name='pastquestionanswerconnector',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='past_question.pastquestions'),
        ),
    ]
