# Generated by Django 3.2 on 2021-11-08 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('past_question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastquestions',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
