# Generated by Django 3.2 on 2021-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_related', '0002_auto_20210410_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='objectives',
        ),
        migrations.AddField(
            model_name='subject',
            name='objectives',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(),
        ),
    ]
